name: FactionsPlus
main: markehme.factionsplus.FactionsPlus
author: ['MarkehMe', 'unv_annihilator']
website: http://markeh.me
version: 0.4.7
depend: [ Factions, Vault ]
soft-depend: [DisguiseCraft, MobDisguise, LWC, WorldGuard]